### ISSUE TITLE
Can this be used as a library for building apps ?

### ISSUE THREAD

**Issue by aelmahmoudy** [mar-v-in/MapsAPI#2]
Hello,

  I've been adding some apps to F-Droid. As you may know already, we patch out Google stuff (analytics,maps,gplay) from the apps we add there. 

I was wondering though, if we instead for apps that need Maps, that we would build them against your MapsAPI ?

If it is possible, other question arise: if a user installs an app from F-Droid which is built against nogapps MapsAPI:
1) Will the user still need to have nogapps-maps.zip flashed on his system ? Or will it be already included in the APK directly ?
2) If the user has GApps installed on his system, will the app then actually call the GApps Maps API or what ?

**Comment by mar-v-in** [comment]
This depends on what you mean by "build against". If you add the MapsAPI as part of the system framework to the build process (the same way you add the android.jar) then the user would need the nogapps-maps.zip or the orginal google maps installed (~= dynamically linked). You can however also include the MapsAPI classes into the resulting binary (~= statically linked). Then the user will always use the MapsAPI, no matter if nogapps-maps or gapps are installed. However the usual problems of statically linking (= fat binaries) also apply here

**Comment by mvdan** [comment]
Thanks @mar-v-in for the clarifications.

Could we have your libraries in F-Droid? What I mean by that is, do they need to be system apps? You supply them via flashable zips instead of just APKs, so I'm assuming that is a yes.

For now there is no way to directly use F-Droid to install system apps. We have a system apps mover though, which would make the trick after the user installed the library in /data.

We're working on adding system level features to F-Droid (super-fdroid branch in git), which I believe would let us install other system apps (correct me if I'm wrong). It's not ready though - feel free to contribute.

**Comment by mar-v-in** [comment]
The MapsAPI is not an app but a shared library. Android supports shared libraries only on the system partition (in form of dalvik jar's in /system/framework/ or as classic compiled libraries in /system/lib).
If you statically link MapsAPI into an app, this app has no need to be a system app.

**Comment by mvdan** [comment]
Perfect, thanks @mar-v-in.
